apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - image: okteto.dev/todo-list
        name: todo-list
        env:
          - name: POSTGRESQL_HOST
            value: db
          - name: POSTGRESQL_USERNAME
            value: okteto
          - name: POSTGRESQL_PASSWORD
            value: okteto
          - name: POSTGRESQL_DATABASE
            value: okteto
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /healthz
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: todo-list
spec:
  type: LoadBalancer
  ports:
  - name: "todo-list"
    port: 8080
  selector:
    app: todo-list
